import type { Config } from "tailwindcss"

const config: Config = {
  darkMode: ["class"],
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#dbe1ff",
        "surface-bright": "#f9f9ff",
        "surface-tint": "#455f87",
        tertiary: "#002a0d",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "on-background": "#111c2d",
        "on-tertiary-fixed": "#002109",
        "on-secondary": "#ffffff",
        surface: "#f9f9ff",
        background: "#f9f9ff",
        "on-secondary-container": "#fefcff",
        "surface-dim": "#cfdaf2",
        "on-tertiary": "#ffffff",
        "inverse-on-surface": "#ecf1ff",
        "secondary-container": "#316bf3",
        "on-secondary-fixed-variant": "#003ea8",
        "on-primary-container": "#8aa4cf",
        "on-error": "#ffffff",
        "inverse-surface": "#263143",
        "surface-container": "#e7eeff",
        secondary: "#0051d5",
        "surface-container-high": "#dee8ff",
        "surface-container-low": "#f0f3ff",
        "on-surface-variant": "#43474e",
        "on-primary-fixed": "#001c3b",
        outline: "#74777f",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#b4c5ff",
        "surface-variant": "#d8e3fb",
        "surface-container-highest": "#d8e3fb",
        "primary-fixed-dim": "#adc8f5",
        "tertiary-fixed": "#7ffc97",
        "on-tertiary-fixed-variant": "#005320",
        primary: "#022448",
        "tertiary-fixed-dim": "#62df7d",
        "on-surface": "#111c2d",
        "on-error-container": "#93000a",
        "inverse-primary": "#adc8f5",
        "on-primary-fixed-variant": "#2d486d",
        error: "#ba1a1a",
        "primary-container": "#1e3a5f",
        "primary-fixed": "#d5e3ff",
        "tertiary-container": "#004319",
        "on-secondary-fixed": "#00174b",
        "outline-variant": "#c4c6cf",
        "on-tertiary-container": "#38b95d",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        xs: "4px",
        lg: "24px",
        sm: "8px",
        gutter: "16px",
        md: "16px",
        unit: "4px",
        xl: "32px",
        margin: "24px",
        "container-max": "1440px",
      },
      fontFamily: {
        sans: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
      },
    },
  },
}

export default config
